# Generated by Django 4.1.1 on 2022-10-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_s', '0002_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.BigIntegerField(verbose_name='Номер телефона'),
        ),
    ]
